server:
  port: 9090
  
spring:
  application:
    name: livecommerce
  profiles:
    active: default
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:mysql://livecommer-manager.cqzajzqaevph.ap-northeast-2.rds.amazonaws.com/livecommerce?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc: 
          batch_size: 5
  rabbitmq:
    host: ec2-13-124-232-201.ap-northeast-2.compute.amazonaws.com
    username: rabbitmq
    password: password123
    
eureka:
  client:
    service-url:
      default-zone: http://192.168.0.24:8761/eureka/
  instance:
    hostname: 192.168.0.24
    
api:
  base-path: http://localhost:9090
  
---
spring:
  profiles: prod
  
# nohup java -jar -Dspring.profiles.active=prod livecommerce-0.0.1-SNAPSHOT.jar >> livecommerce.log &

eureka:
  client:
    service-url:
      # 유레카의 ec2 주소
      defaultZone: http://52.78.12.251:8761/eureka/
  instance:
    # 본인 서비스의 ec2 주소
    hostname: 3.34.97.143
    
api:
  base-path: https://a552eubt4h.execute-api.ap-northeast-2.amazonaws.com/v1/livecommerce