server:
  port: 9090
  
spring:
  application:
    name: livecommerce
  profiles:
    active: default
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:mysql://mysql-1.cqzajzqaevph.ap-northeast-2.rds.amazonaws.com/livecommerce?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc: 
          batch_size: 5
          
  rabbitmq:
    host: ec2-13-124-232-201.ap-northeast-2.compute.amazonaws.com
    username: rabbitmq
    password: password123
    
api:
  base-path: http://localhost:9090